window.PRODUCT_DOCUMENT_RULES = {
  brochure: [
    { models: ["AM2"], file: "product-docs/brochure-specs/ArtMorph-Elite-specifications.png" },
    { models: ["AM6"], file: "product-docs/brochure-specs/ArtMorph-Grande-specifications.png" },
    { models: ["BM2-PC Matte"], file: "product-docs/brochure-specs/BM2-brochure---EN-Dec.-19-2024.jpg" },
    { prefixes: ["BM4"], file: "product-docs/brochure-specs/BM4-brochure---EN-July.-22-2024.jpg" },
    { prefixes: ["BM5"], file: "product-docs/brochure-specs/BM5-brochure-brochure---EN-Feb.-3-2024.jpg" },
    { prefixes: ["BP"], file: "product-docs/brochure-specs/BP2V2-brochure---EN-Feb.-3-2024.jpg" },
    { prefixes: ["BQ"], file: "product-docs/brochure-specs/Black-Quartz-brochure---EN-July.-22-2024.jpg" },
    { prefixes: ["CB"], file: "product-docs/brochure-specs/CB-MKll-brochure---Apr-1-2026.jpg" },
    { prefixes: ["CRS", "CR"], file: "product-docs/brochure-specs/Coral-brochure---Mar-13-2026.jpg" },
    { prefixes: ["DL"], file: "product-docs/brochure-specs/Denali-brochure---Mar-16-2026.jpg" },
    { prefixes: ["EM"], file: "product-docs/brochure-specs/Emerald-brochure-Preview-Feb.-9-2026.jpg" },
    { prefixes: ["GP"], file: "product-docs/brochure-specs/Graphite-brochure---Mar-13-2026.jpg" },
    { prefixes: ["JT"], file: "product-docs/brochure-specs/Jet-brochure---Feb-10-2026---v1.jpg" },
    { prefixes: ["JD"], file: "product-docs/brochure-specs/Jade-brochure-Oct.-30-2025---EN.jpg" },
    { prefixes: ["MRC", "MR"], file: "product-docs/brochure-specs/Meru-Series-brochure---Feb-26-2026.jpg" },
    { prefixes: ["OB"], file: "product-docs/brochure-specs/Obsidian-brochure---EN-Apr.-4-2024.jpg" },
    { prefixes: ["RL"], file: "product-docs/brochure-specs/Rila-brochure---Apr-16-2026.jpg" },
    { prefixes: ["RBC1.9B"], file: "product-docs/brochure-specs/Ruby-C-1.9BV2-brochure---Sep-3-2024.jpg" },
    { prefixes: ["RBC"], file: "product-docs/brochure-specs/Ruby-C-1.5F-1.9F-2.6F-brochure---Feb-10-2026.jpg" },
    { prefixes: ["RB1.2"], file: "product-docs/brochure-specs/Ruby-1.2-brochure---EN-Apr.-23-2024.jpg" },
    { prefixes: ["RB2.2", "RB2.3", "RB2.6"], file: "product-docs/brochure-specs/Ruby-2.2-and-2.6-brochure-EN-Apr.-23-2024.jpg" },
    { prefixes: ["RB"], file: "product-docs/brochure-specs/Ruby-1.5F-1.9F-2.2F-2.6F-VP-brochure.jpg" },
    { prefixes: ["SR"], file: "product-docs/brochure-specs/Sierra-brochure---EN-Preview-Mar.-16-2026.jpg" },
    { prefixes: ["TPC"], file: "product-docs/brochure-specs/Topaz-C-GOB-brochure---Feb-10-2026.jpg" },
    { prefixes: ["TP"], file: "product-docs/brochure-specs/Topaz-brochure---Feb-10-2026.jpg" },
    { prefixes: ["VAI", "VAO"], file: "product-docs/brochure-specs/Vanish-Air-Rental-brochure-preview-Jun.-3-2026.jpg" },
    { prefixes: ["V4ST", "V6ST"], file: "product-docs/brochure-specs/Vanish-ST-brochure---Nov-7-2025.jpg" },
    { prefixes: ["V8T"], file: "product-docs/brochure-specs/V8T-brochure---Nov-7-2025.jpg" },
    { prefixes: ["V5SMK2", "V8SMK2"], file: "product-docs/brochure-specs/Vanish-MKII-brochure---Sep-3-2024.jpg" }
  ],
  simplifiedDrawing: [
    { models: ["AM2"], file: "product-docs/simplified-drawings/previews/CECO_S_AM ELITE WITH MOUNTING BAR_2D.png", pdf: "product-docs/simplified-drawings/pdf/CECO_S_AM ELITE WITH MOUNTING BAR_2D.pdf" },
    { models: ["AM6"], file: "product-docs/simplified-drawings/previews/CECO_S_AM GRAND STANDARD_2D.png", pdf: "product-docs/simplified-drawings/pdf/CECO_S_AM GRAND STANDARD_2D.pdf" },
    { models: ["BM2-PC Matte"], file: "product-docs/simplified-drawings/previews/ROE_S_BM2 matte_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_BM2 matte_2D_V1.0.pdf" },
    { models: ["BM4-Glass"], file: "product-docs/simplified-drawings/previews/ROE_S_BM4 Glass_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_BM4 Glass_2D_V1.0.pdf" },
    { models: ["BM4-Matte"], file: "product-docs/simplified-drawings/previews/ROE_S_BM4 matte_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_BM4 matte_2D_V1.0.pdf" },
    { models: ["BM5-Glass"], file: "product-docs/simplified-drawings/previews/ROE_S_BM5 Glass_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_BM5 Glass_2D_V1.0.pdf" },
    { models: ["BM5i"], file: "product-docs/simplified-drawings/previews/ROE_S_BM5_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_BM5_2D_V1.0.pdf" },
    { prefixes: ["BP"], file: "product-docs/simplified-drawings/previews/ROE_S_BO&BP_2D_v3.1.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_BO&BP_2D_v3.1.pdf" },
    { prefixes: ["BQ"], file: "product-docs/simplified-drawings/previews/BQ Full Tile_2D.png", pdf: "product-docs/simplified-drawings/pdf/BQ Full Tile_2D.pdf" },
    { prefixes: ["CB"], file: "product-docs/simplified-drawings/previews/ROE_S_CB MKII Full Panel_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_CB MKII Full Panel_2D_V1.0.pdf" },
    { prefixes: ["CRS"], file: "product-docs/simplified-drawings/previews/ROE_S_Coral Slim_Panel_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Coral Slim_Panel_2D_V1.0.pdf" },
    { prefixes: ["CR"], file: "product-docs/simplified-drawings/previews/ROE_S_Coral_full Panel_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Coral_full Panel_2D_V1.0.pdf" },
    { prefixes: ["DL"], file: "product-docs/simplified-drawings/previews/ROE_S_Denali_Panel_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Denali_Panel_2D_V1.0.pdf" },
    { prefixes: ["GP"], file: "product-docs/simplified-drawings/previews/ROE_S_Panel_GP_Full_2D_V1.1.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Panel_GP_Full_2D_V1.1.pdf" },
    { prefixes: ["JT"], file: "product-docs/simplified-drawings/previews/ROE_S_Jet_Full Panel_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Jet_Full Panel_2D_V1.0.pdf" },
    { prefixes: ["JDO"], file: "product-docs/simplified-drawings/previews/ROE_S_JDO_Full_2D_V1.0(1).png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_JDO_Full_2D_V1.0(1).pdf" },
    { prefixes: ["MRC"], file: "product-docs/simplified-drawings/previews/ROE_S_MRC_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_MRC_2D_V1.0.pdf" },
    { prefixes: ["MR"], file: "product-docs/simplified-drawings/previews/ROE_S_Meru_Full Panel_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Meru_Full Panel_2D_V1.0.pdf" },
    { models: ["OB2.6"], file: "product-docs/simplified-drawings/previews/ROE_S_OB 2.6_124S02600021_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_OB 2.6_124S02600021_2D_V1.0.pdf" },
    { prefixes: ["RBC"], file: "product-docs/simplified-drawings/previews/ROE_S_RBC TPC_flat_126S02600007_2D_V1.1.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_RBC TPC_flat_126S02600007_2D_V1.1.pdf" },
    { prefixes: ["RL"], file: "product-docs/simplified-drawings/previews/ROE_S_Rila_Panel_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Rila_Panel_2D_V1.0.pdf" },
    { prefixes: ["SR"], file: "product-docs/simplified-drawings/previews/ROE_S_Sierra_Panel_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Sierra_Panel_2D_V1.0.pdf" },
    { models: ["TPC1.9(4in1)"], file: "product-docs/simplified-drawings/previews/ROE_S_RBC TPC_flat_126S02600007_2D_V1.1.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_RBC TPC_flat_126S02600007_2D_V1.1.pdf" },
    { prefixes: ["TPC"], file: "product-docs/simplified-drawings/previews/ROE_S_Topaz-C 2.6_flat_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Topaz-C 2.6_flat_2D_V1.0.pdf" },
    { prefixes: ["TP"], file: "product-docs/simplified-drawings/previews/ROE_S_Topaz Series_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Topaz Series_2D_V1.0.pdf" },
    { models: ["VAO6"], file: "product-docs/simplified-drawings/previews/ROE_S_VAO_Panel_2D.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_VAO_Panel_2D.pdf" },
    { prefixes: ["V5SMK2"], file: "product-docs/simplified-drawings/previews/ROE_S_V5SMKII_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_V5SMKII_2D_V1.0.pdf" },
    { prefixes: ["V8SMK2"], file: "product-docs/simplified-drawings/previews/ROE_S_V8SMKII_2D_V1.0.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_V8SMKII_2D_V1.0.pdf" },
    { prefixes: ["V8T"], file: "product-docs/simplified-drawings/previews/ROE_S_Tile_2D_v1.0_V8T.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_Tile_2D_v1.0_V8T.pdf" },
    { prefixes: ["V4ST", "V6ST"], file: "product-docs/simplified-drawings/previews/ROE_S_VST_1000X1000_2D.png", pdf: "product-docs/simplified-drawings/pdf/ROE_S_VST_1000X1000_2D.pdf" }
  ]
};
